apiVersion: v2
name: metrics-server
description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines.
type: application
version: 0.0.1
appVersion: 0.5.0
keywords:
  - kubernetes
  - metrics-server
  - metrics
home: https://github.com/kubernetes-sigs/metrics-server
icon: https://avatars.githubusercontent.com/u/36015203?s=400&v=4
sources:
  - https://github.com/kubernetes-sigs/metrics-server
dependencies:
- name: metrics-server
  version: 3.10.0
  repository: https://kubernetes-sigs.github.io/metrics-server/